
name: "run godon api image tests"

on:
  pull_request:
    branches:
      - main
    paths:
      - "godon-api/**"

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install tooling
        run: |
          sudo apt-get update
          sudo apt-get install cargo
          sudo cargo install mask --vers 0.11.3
      - name: regenerate api
        run: >
          pushd api && mask api generate && popd;
